version: '3.8'

services:
  cbk-mobile-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3400:80"
    container_name: cbk-mobile-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
